config/routes.rb
Anybuy::Application.routes.draw do

  devise_for :users do
  end

  resources :products

  resources :bids
    match '/bid' => 'bid#biding'

  resources :about do
    collection do
    get :message
    get :home
    end
   end

    match 'help/contact_index' => 'help#contact_index', :via => [:get]
    match 'help/contact_show/:id' => 'help#contact_show', :as => "contact_show", :via => [:get]
    match 'help/contact' => 'help#contact', :via => [:get]
    match 'help/contact_create' => 'help#contact_create', :via => [:post]
    match 'help/contact_destroy/:id' => 'help#contact_destroy', :via => [:delete]
    get "help/tiro"
    get "help/question"

  mount Ckeditor::Engine => '/ckeditor'

  get "member/index"

  get "order/buymoney"

  get "other/clause1"

  get "other/clause2"

   root :to => 'products#index'

end

app/controllers/member_controller.rb
class MemberController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/helpers/member_helper.rb
module MemberHelper
end

app/views/member/_sidebar.html.erb
<div class="row-fluid" id="sidebar">
  <div class="ab-container span3">
    <% if current_user %>
      <h4>會員專區</h4>
      <li><%= link_to '會員管理'.html_safe, edit_registration_path(:user) %></li>
      <li><%= link_to '點數購買'.html_safe, order_buymoney_path %></li>
      <hr />
    <% end %>
      <h4 >幫助</h4>
      <li><%= link_to '新手教學'.html_safe, help_tiro_path %></li>
      <li><%= link_to '常見問題'.html_safe, help_question_path %></li>
      <li><%= link_to '聯絡我們'.html_safe, help_contact_path %></li>
  </div>
</div>

app/views/member/index.html.erb
<%= render :partial => 'member/sidebar' %>

<div class="ab-container span9">
  <h3>會員中心</h3>
    <hr style='border:3px #0047AB;height:2px; background-color:#0047AB; color:#0047AB'>
    <p>歡迎登入AnyBuy會員中心, 您可以透過會員中心修改您的個人資料, 查詢各項競標記錄與購買明細!</p>
    <p>如果有任何關於AnyBuy會員中心的問題, 歡迎聯繫我們, 我們將會為您服務!</p>
  </div>
</div>