config/routes.rb
Anybuy::Application.routes.draw do

  devise_for :users do
  end

  resources :products

  resources :bids
    match '/bid' => 'bid#biding'

  resources :about do
    collection do
    get :message
    get :home
    end
   end

    match 'help/contact_index' => 'help#contact_index', :via => [:get]
    match 'help/contact_show/:id' => 'help#contact_show', :as => "contact_show", :via => [:get]
    match 'help/contact' => 'help#contact', :via => [:get]
    match 'help/contact_create' => 'help#contact_create', :via => [:post]
    match 'help/contact_destroy/:id' => 'help#contact_destroy', :via => [:delete]
    get "help/tiro"
    get "help/question"

  mount Ckeditor::Engine => '/ckeditor'

  get "member/index"

  get "order/buymoney"

  get "other/clause1"

  get "other/clause2"

   root :to => 'products#index'

end

app/controllers/about_controller.rb
# -*- encoding : utf-8 -*-
class AboutController < ApplicationController
  def message
    @messages = Message.order("created_at DESC").page(params[:page]).per(5)
  end
  
  def new
    @message = Message.new  
    respond_to do |format|
      format.html
    end
  end
  
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to :action => :message }
      else
        format.html { render action: "new" }
      end
    end
  end
  
  def edit
    @message = Message.find(params[:id])
  
    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message }
      else
        format.html { render action: "edit" }
      end
    end
  end
  
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to :action => :message}
    end
  end
  
  def home
    @title = "關於我們"
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/_message_form.html.erb
<%= f.input :title, label: '最新消息標題'%><br />

<%= f.input :content, label: '最新消息內容', :as => :ckeditor, :input_html =>{ :ckeditor => {:toolbar => 'mini'} },  hint: '<p style="color:red">※ 發佈最新消息前請再確認一次訊息內容！</p>'%>

app/views/about/home.html.erb
<div class="ab-container main-container">
<h3>關於我們</h3>
  <hr />
</div>

app/views/about/message.html.erb
<div class="ab-container main-container">
  <h3>最新消息</h3>
  <hr />
  <% @messages.each do |message| %>
    <div class="message">
      <div class="message-title">
        <p><%= message.created_at.strftime("%Y-%m-%d") %>&nbsp;&nbsp; <%= message.title %></p>
      </div>

      <div class="message-content">
        <p><%= message.content.html_safe %></p>
      </div>

      <% if current_user && current_user.is_admin? %>
        <%= button_to '刪除' , about_path(message), :method => :delete, :class => 'btn btn-danger'%>
      <% end %>

      <hr>
    </div>
  <% end %>
  <div class="kaminari_message">
    <%= paginate @messages %>
  </div>
</div>

app/views/about/new.html.erb
<div class="ab-container" id="message_new">
  <h4>發佈最新消息</h4>
  <hr />
  <%= simple_form_for @message, :url => about_index_path do |f| %>  
    <%= render :partial => 'message_form', :locals => { :f => f } %>
    <%= f.submit "送出", :class => 'btn btn-success' %>  
    <%= link_to "取消", message_about_index_path, :class => 'btn btn-info' %>
  <% end %>
</div>

app/views/about/news.html.erb
<div class="ab-container main-container">
  <h1>最新消息</h1>
  <p>Find me in app/views/about/news.html.erb</p>
</div>