config/routes.rb
Anybuy::Application.routes.draw do

  devise_for :users do
  end

  resources :products

  resources :bids
    match '/bid' => 'bid#biding'

  resources :about do
    collection do
    get :message
    get :home
    end
   end

    match 'help/contact_index' => 'help#contact_index', :via => [:get]
    match 'help/contact_show/:id' => 'help#contact_show', :as => "contact_show", :via => [:get]
    match 'help/contact' => 'help#contact', :via => [:get]
    match 'help/contact_create' => 'help#contact_create', :via => [:post]
    match 'help/contact_destroy/:id' => 'help#contact_destroy', :via => [:delete]
    get "help/tiro"
    get "help/question"

  mount Ckeditor::Engine => '/ckeditor'

  get "member/index"

  get "order/buymoney"

  get "other/clause1"

  get "other/clause2"

   root :to => 'products#index'

end

app/models/product.rb
# -*- encoding : utf-8 -*-
class Product < ActiveRecord::Base
  has_many :categoriess
  has_many :images, :dependent => :destroy
  has_many :bids
  has_many :users, :through => :bids

  accepts_nested_attributes_for :images
  attr_accessible :title, :description, :price, :images_attributes, :winner_id, :end_at, :categories_id, :primary_price
  validates_presence_of :title, :description, :price, :primary_price, :categories_id, :end_at
  validates_numericality_of :price, :primary_price, :only_integer => true
end

app/controllers/products_controller.rb
# -*- encoding : utf-8 -*-
class ProductsController < ApplicationController
  before_filter :authenticate_user! , :except => [ :show, :index ]

  def index
    @title = "AnyBuy"
    @products_order = Product.where(["created_at > ?" , Time.now - 3.day] ).order("created_at  DESC")
    @products = @products_order.page(params[:page]).per(12)
    @bid_user = User.find_by_sql("SELECT  users.username FROM  products, users
                                       WHERE products.winner_id = users.id")
    respond_to do |format|
      format.html
    end
  end

  def show
    @product = Product.find(params[:id])
    @title = @product.title

    respond_to do |format|
      format.html
    end
  end

  def new
    if current_user && current_user.is_admin
      @title = "新商品上架"
      @product = Product.new
    
      3.times { @product.images.build }
       respond_to do |format|
        format.html
       end
    else
      respond_to do |format|
        format.html { redirect_to :action => :index }
      end
    end
  end

  def edit
    @product = Product.find(params[:id])
    3.times { @product.images.build }
  end

  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to :action => :index }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
    end
  end

end

app/helpers/products_helper.rb
# -*- encoding : utf-8 -*-
module ProductsHelper
end

app/views/products/_form.html.erb
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.input :categories_id, label: '商品類別', prompt:"請選擇商品類別", collection:[["3C數位",1],["服飾配件與美妝",2],["家電,視聽",3],["電玩與玩具",4],["寵物用品與水族",5],["運動休閒與美食",6],["書籍,文具,DVD",7],["傢俱,寢具,收藏",8],["汽機車百貨",9],["禮卷",10]],  :class => "span2" %>
  <%= f.input :title, label:'商品標題' %>
  <%= f.input :description, label:'商品描述', :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} } %>
  <%= f.input :primary_price, label:"商品原價", input_html: {class: 'span2'} %>
  <%= f.input :price, label:"起標價格", input_html: { class: 'span2' } %>
  <%= f.input :end_at, label:'結標時間', start_year: Time.now.year, end_year: Time.now.year, input_html: { class: 'span2' } %>
  <%= f.simple_fields_for :images do |image_form| %>
    <%= image_form.input :image, label: "商品圖片" %>
  <% end %>
  <span style="color:red;">※ 商品圖片請至少上傳一張</span>
</div>

app/views/products/edit.html.erb
<div class="ab-container">
  <h1>Editing product</h1>
  <%= form_for @product, :url => product_path(@product), :html => { :multipart => true } do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "送出" %>
  <% end %>
  <%= link_to 'Show', @product %> |
  <%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item">
      <%= image_tag("01.jpg") %>
    </div>
    <div class="item active">
      <%= image_tag("02.jpg") %>
    </div>
    <div class="item">
      <%= image_tag("03.jpg") %>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
</div>

<div id="products" class="ab-container main-container">
  <ul>
    <% @products.each do |product| %>
      <li class="thumbnail countdown_holder">
        <%= link_to product.title, product, :class => "title" %>
        <% for image in product.images.limit(1) %>
          <div class="index-img" style="background-image:url(<%= image.image.url(:medium)  %>)" >
          </div>
        <% end %>
        <% @time = product.end_at.to_i %>
        <%= content_tag(:span, "--:--:--",:class => "countdown countthis", :time => @time) %>
        <%= content_tag :span, :class => "price" do %>
          <%= product.price %>元<br />
        <% end %>
        <% @bid_user.each do |user| %>
          <%= user.username %><br />
        <% end %>
        <%= button_to "下標", { :controller => 'bid', :action => 'biding'}, :id => product.id  , :class => "bidsubmit btn btn-warning", :disabled => true %>
        <% if current_user && current_user.is_admin? %>
          <%= button_to '刪除' , product_path(product), :method => :delete, :class => 'btn btn-danger' %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>
<div class="kaminari_products">
  <%= paginate @products %>
</div>

app/views/products/new.html.erb
<div class="ab-container", id="product_new">
  <h4>商品上架</h4>
  <hr>
  <%= simple_form_for @product, :url => products_path, :html => { :multipart => true } do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %> <br />
    <%= f.submit "送出", :class => 'btn btn-success' %>
    <%= link_to '取消上架', products_path, :class => 'btn btn-info' %>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="ab-container" id="product_show">
  <p id="notice"><%= notice %></p>
  <div class="product_title">
    <div class="breadcrumbs">
      <%= link_to '首頁', products_path %> <span class="breadcromb-separate">/</span> <%= Categories.find(@product.categories_id)[:ptitle] %>
    </div>
    <h3 class="text-success"><%= @product.title %></h3>
  </div>
  <div class="product_info">
    <div class="photos">
      <% for image in @product.images.limit(1) %>
        <div class="image main" style="background-image:url(<%= image.image.url(:medium)  %>)" ></div>
      <% end %>
      <% for image in @product.images.limit(2) %>
        <div class="image thmbnl" style="background-image:url(<%= image.image.url(:medium)  %>)" ></div>
      <% end %>
    </div>
    <div class="bid-info countdown_holder">
      <div class="price"><%= @product.price %>元</div>
        <% @time = @product.end_at.to_i %>
        <%= content_tag(:span, "--:--:--",:class => "countdown countthis", :time => @time) %>
        <div class="picture"><img src="http://placehold.it/70x70"/></div>
          <%= button_to "下標", { :controller => 'bid', :action => 'biding'}, :id => @product.id  , :class => "bidsubmit btn btn-warning", :disabled => true %>
          <ul class="current-bid">
            <li class="highlight">金額：<span class="value"><%= @product.price %>元</span></li>
            <li>目前贏家：<span class="value"></span></li>
            <li>商品定價：<span class="value"><%= @product.primary_price %>元</span></li>
            <li>目前競標價格：<span class="value"><%= @product.price %>元</span></li>
            <li><hr/></li>
            <li>立即購買金額：<span class="value"><%= @product.primary_price %>元</span></li>
          </ul>
          <form onsubmit="return false;">
            <button class="btn btn-primary span2 buy_now">直接購買<br/></button>
          </form>
        </div>
        <div class="bid-history">
          <div class="history-title">投標紀錄</div>
            <table class="table table-striped">
              <tr>
                <th class="text-center">金額</th>
                <th class="text-center">競標者</th>
                <th class="text-center">???</th>
              </tr>
              <tr>
                <td>100</td>
                <td class="text-center">Andy</td>
                <td class="text-center">ooxx</td>
              </tr>
              <tr>
                <td>100</td>
                <td class="text-center">Andy</td>
                <td class="text-center">ooxx</td>
              </tr>
              <tr>
                <td>100</td>
                <td class="text-center">Andy</td>
                <td class="text-center">ooxx</td>
              </tr>
              <tr>
                <td>100</td>
                <td class="text-center">Andy</td>
                <td class="text-center">ooxx</td>
              </tr>
            </table>
            <div class="auto-bid form-horizontal">
              <div class="title">自動下標</div>
              <div class="control-group"><div class="control-label">當競標達到</div> <div class="controls"><input type="text" class="span1"/> 元</div></div>
              <div class="control-group"><div class="control-label">開始自動下標</div> <div class="controls"><input type="text" class="span1"/> 次</div></div>
              <div class="button-row"><button class="btn btn-warning">開始自動</button></div>
            </div>
          </div>
        </div>
        <hr>
        <div class="bid_description">
          <ul class="sp">
            <li><h4>競標注意事項</h4></li>
            <li>每下標一次需消費 1 點。下標所消費的點數無論是最後是否得標均無法退還。 </li>
            <li>非限量商品及非點數下標所消費的點數如未得標可使用立即購買折換為現金，於待繳金額中扣除。</li>
            <li>限量商品以及點數競標是無法進行直接購買，若未得標，您於競標使用的點數，也無法退還。</li>
            <li>參與競標時，系統會隨機配發一組競標專屬暱稱。結標後，紀錄會調整為真實會員暱稱，以示競標真實性。</li>
            <li>畫面所顯示的剩餘時間及下標狀況，有可能因各人網路連線品質造成延遲現象。</li>
            <li>本站準時結標，如因使用手機或低速無線網路連線，造成來不及下標，將不另作補償。 建議使用 Chrome，Firefox 及 Safari 的瀏覽器。</li>
            <li>考量各會員頻寬不同，系統有可能在 0 秒後處理最後送入系統的下標資料，若於 0 秒後投標，非正常投標，無法保證可被接受。</li>
            <li>本站無法保證每場拍賣的商品，您都能得標或以低價獲得。</li>
            <li>網站主要的營運時間為上午 15:00 到 晚上 02:30，過了網站營運時間，所有正在競標中的商品結標時間會自動延長 12.5 小時。</li>
            <hr>
            <li><h4>商品詳細介紹</h4></li>
            <li><%= @product.description.html_safe %></li>
            <hr>
            <li><h4>付款資訊</h4></li>
            <li>付款方式    ATM轉帳 / 信用卡線上付款 / iBon / 貨到付款</li>
            <li>運費和手續費  120 元</li>
            <li>購買限制說明   請於本商品得標後的48小時內選擇付款方式如有任何相關問題，請<%= link_to "與我們聯絡",  help_contact_path %>。</li>
          </ul>
        </div>
</div>