config/routes.rb
Anybuy::Application.routes.draw do

  devise_for :users do
  end

  resources :products

  resources :bids
    match '/bid' => 'bid#biding'

  resources :about do
    collection do
    get :message
    get :home
    end
   end

    match 'help/contact_index' => 'help#contact_index', :via => [:get]
    match 'help/contact_show/:id' => 'help#contact_show', :as => "contact_show", :via => [:get]
    match 'help/contact' => 'help#contact', :via => [:get]
    match 'help/contact_create' => 'help#contact_create', :via => [:post]
    match 'help/contact_destroy/:id' => 'help#contact_destroy', :via => [:delete]
    get "help/tiro"
    get "help/question"

  mount Ckeditor::Engine => '/ckeditor'

  get "member/index"

  get "order/buymoney"

  get "other/clause1"

  get "other/clause2"

   root :to => 'products#index'

end

app/views/common/_user_nav.erb
<% if current_user %>
  <li class="dropdown">
    <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
      <%= current_user.username %>
      <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to '<i class="icon-user"></i> 會員中心'.html_safe, edit_registration_path(:user) %></li>
        <% if current_user && current_user.is_admin %>
          <li><%= link_to '<i class="icon-plus" ></i> 商品上架'.html_safe, new_product_path %></li>
          <li><%= link_to '<i class="icon-comment" ></i> 發佈最新消息'.html_safe, new_about_path %></li>
          <li><%= link_to '<i class=" icon-envelope"></i> 客服專區'.html_safe,  help_contact_index_path %></li>
        <% end %>
          <li><%= link_to( '<i class="icon-off"></i> 登出'.html_safe, destroy_user_session_path, :method => :delete) %></li>
        </ul>
  </li>
<% else %>
  <li><%= link_to '註冊', new_registration_path(:user) %></li>
  <li><%= link_to "登入", new_session_path(:user) %></li>
<% end %>